import type React from 'react'
import { isSameCalendarDay, toDate } from './date'

/** A single message entry managed by {@link Chat}. */
export interface GroupedMessage {
  /** Unique React key — auto-generated by `<Chat>` when omitted. */
  id?: React.Key
  /** Identifies the sender; `'me'` denotes the local user. */
  senderId: string
  /** The rendered message node, typically a `<Message>` component tree. */
  node: React.ReactNode
  /** Creation timestamp; used to group messages by calendar day and compute day-divider labels. */
  timestamp?: Date | string
}

/** A run of consecutive messages from the same sender on the same calendar day. */
export interface MessageDayGroup {
  /** Sender id shared by all messages in this group. */
  senderId: string
  /** The calendar day for this group, or `null` when no timestamp was provided. */
  dayDate: Date | null
  /** Ordered list of messages belonging to this group. */
  messages: GroupedMessage[]
}

/** Groups a flat message list into per-sender, per-day segments. */
export function groupMessagesByDay(messages: GroupedMessage[]): MessageDayGroup[] {
  return messages.reduce<MessageDayGroup[]>((groups, message) => {
    const lastGroup = groups[groups.length - 1]
    const currentDate = toDate(message.timestamp)
    const lastMessage = lastGroup?.messages[lastGroup.messages.length - 1]
    const lastDate = toDate(lastMessage?.timestamp)
    const isSameDayAsLast =
      currentDate && lastDate ? isSameCalendarDay(currentDate, lastDate) : true

    if (lastGroup && lastGroup.senderId === message.senderId && isSameDayAsLast) {
      lastGroup.messages.push(message)
      return groups
    }

    groups.push({ senderId: message.senderId, dayDate: currentDate, messages: [message] })
    return groups
  }, [])
}
